<?php

$JSON = '{
    "data": [
        {
            "id": "1816023336543838208",
            "type": 1,
            "subType": null,
            "category": "企业介绍",
            "style": "扁平简约",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "蓝色主题简约商务模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1816023336543838208.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=JmXA41twoC58CfP%2FqhdzxvW0Uvo%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3720,
            "num": 26,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-07-26 10:38:52",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1805081814809960448",
            "type": 1,
            "subType": null,
            "category": null,
            "style": null,
            "themeColor": null,
            "lang": "zh",
            "animation": null,
            "subject": "",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1805081814809960448.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=9ruEnO1YBLfF3c0u6QZHAGS8O%2BI%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 80,
            "num": 30,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-12 15:26:38",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815334914816729088",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "扁平简约",
            "themeColor": "#FFFFFF",
            "lang": "zh",
            "animation": false,
            "subject": "白色简约答辩演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815334914816729088.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=7IbsJu7TiUQ%2Ba2WWcOIpZ0j5DO4%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 2920,
            "num": 30,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-06 18:10:18",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1810202494165573632",
            "type": 1,
            "subType": null,
            "category": "医学医疗",
            "style": "商务科技",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "浅蓝色医疗生物主题工作总结汇报演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1810202494165573632.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=3e0eIKMghHB4UYTm9gxUFOVa4nE%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 2400,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-07 12:03:02",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815673143831027712",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "卡通手绘",
            "themeColor": "#7664FA",
            "lang": "zh",
            "animation": false,
            "subject": "紫色卡通手绘通用演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815673143831027712.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=WzInWYrh7bEPPca0leb1UOHUhxk%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3320,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-02 13:55:16",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815585249871257600",
            "type": 1,
            "subType": null,
            "category": "商业计划书",
            "style": "商务科技",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "蓝色商业计划书通用演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815585249871257600.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=xNqo5A95oNMQaPkDiH%2BTvccObD8%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3040,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-06 10:34:58",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1792777377043132416",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "中国风",
            "themeColor": "#FA920A",
            "lang": "zh",
            "animation": false,
            "subject": "创意油画背景演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1792777377043132416.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=aMjHdJj7PVwZh3YImCCOG926dIo%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 1180,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-20 11:03:35",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1807659875694796800",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "文艺清新",
            "themeColor": "#61D328",
            "lang": "zh",
            "animation": false,
            "subject": "绿色清新自然主题演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1807659875694796800.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=FkdfkO4Q4FGtH%2BFgG%2FGVkhN%2F778%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 600,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-14 15:04:52",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1808025604461944832",
            "type": 1,
            "subType": null,
            "category": "商业计划书",
            "style": "商务科技",
            "themeColor": "#7664FA",
            "lang": "zh",
            "animation": false,
            "subject": "紫色科技商务主题演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1808025604461944832.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=MLvNVl3DxS2yJEyvO4eO8vZ9Nak%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 980,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-15 16:35:11",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815291863360593920",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "扁平简约",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "极简风商务工作报告演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815291863360593920.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=5Dugwktz05eHjofycT3HGPukUqA%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 2620,
            "num": 29,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-15 17:40:03",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1809201240576614400",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "商务科技",
            "themeColor": "#000000",
            "lang": "zh",
            "animation": false,
            "subject": "黑金色金融工作主题演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1809201240576614400.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=%2BcYlJtFfI60o8YmeRiHSr2dHoQY%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 2320,
            "num": 29,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-15 17:19:34",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1808773451012628480",
            "type": 1,
            "subType": null,
            "category": "企业介绍",
            "style": "扁平简约",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "蓝色通用主题模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1808773451012628480.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=IThq0E6GfUCm%2FgJrR3bdOE8Alr0%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 1980,
            "num": 29,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-14 11:22:40",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1807686611094462464",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "创意时尚",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "渐变色艺术风格演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1807686611094462464.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=LJ5l6v%2BTFS73eQ9QGju02dssdZk%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 780,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-14 17:53:41",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1807663800703508480",
            "type": 1,
            "subType": null,
            "category": "商业计划书",
            "style": "商务科技",
            "themeColor": "#E05757",
            "lang": "zh",
            "animation": false,
            "subject": "酒红色时尚商务演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1807663800703508480.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=El6YyBBUrQxhk7WU8ITvZfwybR8%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 640,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-14 16:07:42",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815630950042951680",
            "type": 1,
            "subType": null,
            "category": "商业计划书",
            "style": "商务科技",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "蓝色研究课题答辩演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815630950042951680.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=kzT3IC40aQY24ycrZi2ZraYJKOk%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3120,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-15 20:09:53",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1806268304982269952",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "扁平简约",
            "themeColor": "#000000",
            "lang": "zh",
            "animation": false,
            "subject": "大气简约工作通用演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1806268304982269952.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=5AUStnRZ6TVSs%2BVRt2WZJeGbLq4%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 220,
            "num": 29,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-13 14:08:42",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1816008514972409856",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "商务科技",
            "themeColor": "#7664FA",
            "lang": "zh",
            "animation": false,
            "subject": "紫色项目计划书演示模板\t",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1816008514972409856.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=dQHDNALTpFU%2BrYVux%2Be5UXMiz90%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3680,
            "num": 26,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-07-31 17:47:16",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1808020295823646720",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "中国风",
            "themeColor": "#65E5EC",
            "lang": "zh",
            "animation": false,
            "subject": "古典书画风格主题演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1808020295823646720.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=ZL7i3mHZ%2BdC6o2Tk0WVzHE7V8SQ%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 940,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-20 17:24:05",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1806285286083387392",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "商务科技",
            "themeColor": "#FFFFFF",
            "lang": "zh",
            "animation": false,
            "subject": "深灰商务时尚演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1806285286083387392.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=zB8BaDNTPb%2BEJieGEeO0oy0Pe40%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 300,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-13 16:25:56",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815635262324334592",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "卡通手绘",
            "themeColor": "#7664FA",
            "lang": "zh",
            "animation": false,
            "subject": "紫色简约插画工作总结通用演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815635262324334592.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=S82odquAY0ZEbgK9kXADaxM36pw%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3140,
            "num": 29,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-15 20:08:45",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1806291734771261440",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "卡通手绘",
            "themeColor": "#7664FA",
            "lang": "zh",
            "animation": false,
            "subject": "紫色扁平插画风格演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1806291734771261440.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=0YPb29VUhpCHckm7ozokTZTsdpQ%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 380,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-13 17:38:34",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1792829270024990720",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "商务科技",
            "themeColor": "#000000",
            "lang": "zh",
            "animation": false,
            "subject": "气泡彩膜主题演示模版",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1792829270024990720.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=mWVMQzMXywi7F%2FRUzO76gNhmCIk%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 1060,
            "num": 33,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-08 11:26:45",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1792468347829563392",
            "type": 1,
            "subType": null,
            "category": "商业计划书",
            "style": "商务科技",
            "themeColor": "#000000",
            "lang": "zh",
            "animation": true,
            "subject": "黑色科技风格",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1792468347829563392.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=8pok0uPXMJoOyvhRq2jvuhBkx4g%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 1140,
            "num": 31,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-06-28 10:04:37",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1792408621909413888",
            "type": 1,
            "subType": null,
            "category": "商业计划书",
            "style": "商务科技",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": true,
            "subject": "蓝色简约商务",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1792408621909413888.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=j2UiLklv2i%2BsQLfGafKdguNit5w%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 1100,
            "num": 29,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-06-28 10:38:42",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815308477845987328",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "文艺清新",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "蓝色清新可爱风格海洋主题演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815308477845987328.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=rXvSzznFQ%2B3EMYGRcYtQUV9Wz6Q%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 2820,
            "num": 27,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-07 14:01:20",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815663444272340992",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "商务科技",
            "themeColor": "#E05757",
            "lang": "zh",
            "animation": false,
            "subject": "红色商业计划演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815663444272340992.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=VNIbyhgZT6PJ5OjgAbpdZLl7UcQ%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3240,
            "num": 28,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-02 19:45:30",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1815644223555493888",
            "type": 1,
            "subType": null,
            "category": "年终总结",
            "style": "卡通手绘",
            "themeColor": "#7664FA",
            "lang": "zh",
            "animation": false,
            "subject": "紫色手绘插画风格工作总结汇报通用演示模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1815644223555493888.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=kHyprdqJmgQnu%2FQBZ0cNFEACcnE%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3160,
            "num": 30,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-08-05 14:58:12",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        },
        {
            "id": "1816014257578565632",
            "type": 1,
            "subType": null,
            "category": "企业介绍",
            "style": "扁平简约",
            "themeColor": "#589AFD",
            "lang": "zh",
            "animation": false,
            "subject": "蓝色主题简约模板",
            "coverUrl": "https://meta-doc.oss-cn-shanghai.aliyuncs.com/ppt_template/1816014257578565632.png?Expires=1727067114&OSSAccessKeyId=LTAI5tAfZYeAw8hN3gDzs7sx&Signature=tIc2JSt9S%2BQrH%2FVVefdyxonE9oQ%3D",
            "fileUrl": null,
            "pptxProperty": null,
            "sort": 3700,
            "num": 26,
            "isDeleted": 0,
            "userId": null,
            "companyId": -1,
            "createTime": "2024-07-25 13:48:37",
            "updateUser": null,
            "updateTime": null,
            "createUser": null
        }
    ],
    "code": 0,
    "message": "ok"
}';

header("Content-Type: application/json");
require_once('../cors.php');
require_once('../include.inc.php');
ini_set('max_execution_time', 7200);

$JSONARRAY = json_decode($JSON, true)['data'];

foreach($JSONARRAY as $Item)   {
    $Element = [];
    $Element['编码']  = $Item['id']; 
    $Element['目录']  = $Item['category']; 
    $Element['风格']  = $Item['style']; 
    $Element['皮肤颜色']  = $Item['themeColor']; 
    $Element['语言']  = 'zh-CN'; 
    $Element['主题']  = $Item['subject']; 
    $Element['封面URL']  = $Item['id']; 
    $Element['排序']  = $Item['sort']; 
    $Element['页码']  = $Item['num']; 
    if($Item['id']!="" && $Element['风格']!='')   {
        [$Record,$sql] = InsertOrUpdateTableByArray("data_ai_pptx_templates", $Element, '编码', 0);
        print $sql."<BR>";
    }

}


?>